# Generated by Django 2.1.3 on 2018-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, choices=[('москва', 'москва'), ('санкт-питербург', 'санкт-питербург'), ('екатеринбург', 'екатеринбург'), ('казань', 'казань')], default='екатеринбург', help_text='Выберите город из списка ', max_length=200, verbose_name='Город'),
        ),
    ]
