# Generated by Django 2.1.4 on 2018-12-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='news_and_info',
            field=models.BooleanField(verbose_name='новости и информация'),
        ),
    ]
