# Generated by Django 2.1.3 on 2018-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField(verbose_name='integer')),
                ('positive_field', models.PositiveIntegerField(verbose_name='positive')),
                ('positive_small_field', models.PositiveSmallIntegerField(verbose_name='positive small')),
                ('big_integer_field', models.BigIntegerField(verbose_name='big integer')),
                ('float_field', models.FloatField(verbose_name='float')),
                ('binary_field', models.BinaryField(verbose_name='binary')),
                ('boolean_field', models.BooleanField(verbose_name='boolean')),
                ('char_field', models.CharField(max_length=5, verbose_name='char')),
                ('text_field', models.TextField(max_length=20, verbose_name='text')),
                ('data_field', models.DateField(auto_now=True, verbose_name='data')),
                ('data_time_field', models.DateTimeField(auto_now_add=True, verbose_name='data time')),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='decimal')),
                ('email_field', models.EmailField(max_length=254, verbose_name='email')),
                ('file_field', models.FileField(upload_to='files', verbose_name='file')),
                ('image_field', models.ImageField(upload_to='images', verbose_name='image')),
            ],
        ),
    ]
