# Generated by Django 2.1.3 on 2018-11-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50, verbose_name='заголовок статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['headline'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('patronymic', models.CharField(max_length=50, verbose_name='отчество автора')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия автора')),
                ('date_birth', models.DateField(verbose_name='дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название книги')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='текст')),
                ('genre', models.CharField(choices=[('комедия', 'комедия'), ('трагедия', 'трагедия'), ('драма', 'драма')], default='драма', max_length=50, verbose_name='жанр')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Author', verbose_name='автор книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название ресторана')),
                ('address', models.CharField(max_length=80, verbose_name='адрес ресторана')),
            ],
            options={
                'verbose_name': 'Адрес ресторана',
                'verbose_name_plural': 'Адреса ресторанов',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='название газеты')),
            ],
            options={
                'verbose_name': 'Газета',
                'verbose_name_plural': 'Газеты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serves_hot_dogs', models.BooleanField(default=False, verbose_name='заказ хот догов')),
                ('serves_pizza', models.BooleanField(default=False, verbose_name='заказ пиццы')),
                ('serves_steak', models.BooleanField(default=False, verbose_name='заказ стайков')),
                ('serves_burgers', models.BooleanField(default=False, verbose_name='заказ бургеров')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_models.Place', verbose_name='адрес ресторана')),
            ],
            options={
                'verbose_name': 'Ретсоран',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='TestModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField(verbose_name='integer')),
                ('positive_field', models.PositiveIntegerField(verbose_name='positive')),
                ('positive_small_field', models.PositiveSmallIntegerField(verbose_name='positive small')),
                ('big_integer_field', models.BigIntegerField(verbose_name='big integer')),
                ('float_field', models.FloatField(verbose_name='float')),
                ('binary_field', models.BinaryField(verbose_name='binary')),
                ('boolean_field', models.BooleanField(verbose_name='boolean')),
                ('char_field', models.CharField(max_length=5, verbose_name='char')),
                ('text_field', models.TextField(blank=True, max_length=20, verbose_name='text')),
                ('data_field', models.DateField(verbose_name='data')),
                ('data_time_field', models.DateTimeField(verbose_name='data time')),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='decimal')),
                ('email_field', models.EmailField(max_length=254, verbose_name='email')),
                ('file_field', models.FileField(blank=True, upload_to='files', verbose_name='file')),
                ('image_field', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Пример полей',
                'verbose_name_plural': 'Примеры полей',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя официанта')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Restaurant', verbose_name='название ресторана')),
            ],
            options={
                'verbose_name': 'Официант',
                'verbose_name_plural': 'Официанты',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ManyToManyField(to='test_models.Publication', verbose_name='публикация'),
        ),
    ]
