# Generated by Django 2.1.3 on 2018-11-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('patronymic', models.CharField(max_length=50, verbose_name='отчество автора')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия автора')),
                ('date_birth', models.DateField(verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название книги')),
                ('text', models.TextField(max_length=1000, verbose_name='текст')),
                ('genre', models.CharField(choices=[('comedy', 'комедия'), ('tragedy', 'трагедия'), ('drama', 'драма')], max_length=50, verbose_name='жанр')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Author', verbose_name='автор книги')),
            ],
        ),
        migrations.AlterField(
            model_name='testmodels',
            name='data_field',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='testmodels',
            name='data_time_field',
            field=models.DateTimeField(verbose_name='data time'),
        ),
    ]
