# Generated by Django 2.1.3 on 2018-11-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_auto_20181125_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название ресторана')),
                ('address', models.CharField(max_length=80, verbose_name='адрес ресторана')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serves_hot_dogs', models.BooleanField(default=False, verbose_name='заказ хот догов')),
                ('serves_pizza', models.BooleanField(default=False, verbose_name='заказ пиццы')),
                ('serves_steak', models.BooleanField(default=False, verbose_name='заказ стайков')),
                ('serves_burgers', models.BooleanField(default=False, verbose_name='заказ бургеров')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_models.Place', verbose_name='адрес ресторана')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя официанта')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Restaurant', verbose_name='название ресторана')),
            ],
        ),
    ]
