# Generated by Django 2.1.3 on 2018-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0003_place_restaurant_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50, verbose_name='заголовок')),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='название статьи')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ManyToManyField(to='test_models.Publication', verbose_name='публикация'),
        ),
    ]
