# Generated by Django 2.1.3 on 2018-11-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0004_auto_20181125_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('headline',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Адрес ретсорана', 'verbose_name_plural': 'Адреса ресторанов'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('title',), 'verbose_name': 'Газета', 'verbose_name_plural': 'Газеты'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ретсоран', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterModelOptions(
            name='testmodels',
            options={'verbose_name': 'Пример полей', 'verbose_name_plural': 'Примеры полей'},
        ),
        migrations.AlterModelOptions(
            name='waiter',
            options={'verbose_name': 'Официант', 'verbose_name_plural': 'Официанты'},
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=50, verbose_name='заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=30, verbose_name='название газеты'),
        ),
    ]
