# Generated by Django 2.1.3 on 2018-11-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0005_auto_20181125_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Адрес ресторана', 'verbose_name_plural': 'Адреса ресторанов'},
        ),
    ]
