# Generated by Django 2.1.3 on 2018-11-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0006_auto_20181125_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['headline'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['title'], 'verbose_name': 'Газета', 'verbose_name_plural': 'Газеты'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('комедия', 'комедия'), ('трагедия', 'трагедия'), ('драма', 'драма')], max_length=50, verbose_name='жанр'),
        ),
    ]
