# Generated by Django 2.1.3 on 2018-11-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0007_auto_20181126_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('комедия', 'комедия'), ('трагедия', 'трагедия'), ('драма', 'драма')], default='драма', max_length=50, verbose_name='жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='текст'),
        ),
    ]
