# Generated by Django 2.1.3 on 2018-11-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0008_auto_20181126_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodels',
            name='file_field',
            field=models.FileField(blank=True, upload_to='files', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='testmodels',
            name='image_field',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testmodels',
            name='text_field',
            field=models.TextField(blank=True, max_length=20, verbose_name='text'),
        ),
    ]
